In [1]:
from ris import db2  #library designed for SQL database connection and querying
from IPython.display import clear_output
from collections import defaultdict
from collections import defaultdict, namedtuple
import datetime 
import pandas as pd
import numpy as np
import os
from sqlalchemy import create_engine
import pwa_node_universe_1106 as nu
from Df_to_PG import* 

clear_output()
timestamp = datetime.datetime.now().strftime('%Y-%m-%d_%H:%M')
ts = datetime.datetime.now().strftime('%Y-%m-%d')
print 'Notebook run: {}'.format(timestamp)
print os.getcwd()
# %load_ext sql

Notebook run: 2020-02-04_14:22
E:\RIS\Staff Folders\Samuel\Requests\SH\PWA\Most Recent\Final

In [2]:
cdb = db2.PostgresDb('DOTDEVRHPGSQL01', 'CRASHDATA', quiet = True)
gdb = db2.SqlDb('dotgissql01', 'gisgrid', user='GISUSER', db_pass='GISUSER') #Database Connection
msdb = db2.SqlDb('DOT55SQL01', 'DataWarehouse', user='arcgis', db_pass='arcgis') #Database Connection

User name (CRASHDATA):soge
Password (CRASHDATA)········

In [47]:
#@db2.timeDec
def xy_to_geom(cdb,*args): 
    
    """
    Function that generates the hexidecimal geomteric string 
    of every input coordinate. 
   
    Args:
        cdb param: Database Connection Function for PostgreSQL 
        
    *args
        xy arg: X,Y coordinates 
                format: [[x,y][x,y]] or xy=[x,y] or input x=x,y=y

    Returns:
        geom (str): Hexidecimal geomteric string 
        
    
    e.g.
    
    Input:
    
    xy_to_geom(cdb,[[1000245.0, 202806.0],[1000537.9999999995, 186726.9999999482],[1002334.9999999987, 250597.99999993874]])
    
    Returns:
    
    ['0101000020D7080000000000006A862E4100000000B0C10841',
     '0101000020D708000000000000B4882E410000000038CB0641']
    """
    
   
    
    try:
        
        if any(isinstance(item, list) for item in args[0]):  #args is a tuple 
            print('TRUE')
            count=0
            geom =[None]*len(args[0])
            for i in args[0]:
                g=cdb.query("select ST_GeomFROMText('POINT(' || {x}::text || ' ' ||  {y}::text || ')', 2263) geom ".format(x=i[0],y=i[1]))
                #print(g)
                geom[count]=g[0][0][0]
                count+=1

        else:
            #print(args[0])
            if isinstance(args[0], list):
                g = cdb.query("select ST_GeomFROMText('POINT(' || {x}::text || ' ' ||  {y}::text || ')', 2263) geom".format(x=args[0][0],y=args[0][1]))
                geom = g[0][0][0]

    except:
    
        xy = list(args)
        #print(lon_lat)
        g = cdb.query("select ST_GeomFROMText('POINT(' || {x}::text || ' ' ||  {y}::text || ')', 2263) geom".format(x=xy[0],y=xy[1]))
        geom = g[0][0][0]

    return geom

In [48]:
#@db2.timeDec

def lon_lat_to_geom(cdb,*args): #input either list of list [[lon,lat][lon,lat]] or list lon_lat=[lon,lat] or input lon=lon,lat=lat 
    
    """
    Function that generates the hexidecimal geomteric string 
    of every input coordinate. 
   
    Args:
        cdb param: Database Connection Function for PostgreSQL 
        
    *args
        lon_lat arg (float): Longitude,Latitude coordinates 
                             format: [[lon,lat][lon,lat]] or [lon,lat] or input lon=lon,lat=lat

    Returns:
        geom (str): Hexidecimal geomteric string 
        
    
    e.g.
    
    Input:
    
    lon_lat_to_geom(cdb,[[-73.99247600,40.71507200],[-73.99247600,40.71507200]])
    
    Returns:
    
    ['0101000020D7080000D5011E94BF192E41347ACDE4A4630841',
     '0101000020D7080000D5011E94BF192E41347ACDE4A4630841']
    """
    
    
  
   
    try:
        if any(isinstance(item, list) for item in args[0]): 
            #print('TRUE')
            count=0
            geom =[None]*len(args[0])
            for i in args[0]:
                #print(i)
                g= cdb.query("select st_transform(ST_PointFromText('POINT(' || {lon} || ' ' || {lat} || ')', 4326), 2263) geom ".format(lon=i[0],lat=i[1]))
                #print(g)
                geom[count]=g[0][0][0]
                count+=1

        else:
            #print(args[0])
            if isinstance(args[0], list):
                g = cdb.query("select st_transform(ST_PointFromText('POINT(' || {lon} || ' ' || {lat} || ')', 4326), 2263) geom ".format(lon=args[0][0],lat=args[0][1]))
                geom = g[0][0][0]

    except:
        lon_lat = list(args)
        #print(lon_lat)
        g = cdb.query("select st_transform(ST_PointFromText('POINT(' || {lon} || ' ' || {lat} || ')', 4326), 2263) geom ".format(lon=lon_lat[0],lat=lon_lat[1]))
        geom = g[0][0][0]

    return geom

In [49]:
def geom_to_lonlat(geom,cdb):
    
    result = cdb.query("""    
                       select ST_AsText(st_transform('{}'::text,4326))
                       """.format(geom))
    
    return result.data[0][0].strip('POINT()').split()

In [50]:
def dist(geom1, geom2):
    
    result =  cdb.query("""select st_distance('{geom1}'::geometry, '{geom2}'::geometry) as distance""")
                       
    return result

In [51]:
def to_itx(cdb,**args): 
    
    """
    Function that retrieves nearest intersection from the location
    of input control signal
   
    Args:
        cdb param: Database Connection Function for PostgreSQL
        
    *args:
        rad (int, optional): Search radius for locating nearest node from all way stop
        xy arg (optional if geom given): X,Y coordinates of all way stop
                                         format: [[x,y][x,y]] or xy=[x,y] or input x=x,y=y
        lon_lat arg (optional if geom given): Longitude,Latitude coordinates 
                                              format: [[lon,lat][lon,lat]] or [lon,lat] or input lon=lon, lat=lat
        geom arg (str, optional if xy or lon_lat given): Hexidecimal geomteric string X,Y coordinates of all way stop
        
    Returns:
        result (dataFrame): Nodeid, Distance between Nodeid and Control Signal, Nodeid Geometry, Control geometry, Coordinates
        val (int): 0 if no args given`    
        
    e.g.
    
    Input:
    
    to_itx(cdb,xy=[1000537.9999999995, 186726.9999999482],geom='0101000020D708000000000000B4882E410000000038CB0641')
    
    Returns:
    
    nodeid  distance    node_geom                   control_geom                xy
    26723   0.0340567   0101000020D7080000009...    0101000020D7080000000...    [1000538.0, 186727.0]
    """  
    
    db= cdb
    rad = args.get('rad', 50)  
    geom = args.get('geom', 0)
    xy = args.get('xy', 0)
    lon_lat= args.get('lon_lat', 0)
    coor = lambda x: map(float,x.replace('[','').replace(']','').split(','))  
    
         
    if len(args)==0:
            return 0
    
    if geom==0:
        if xy:
            geom = xy_to_geom(db,xy)
        else:
            geom = lon_lat_to_geom(db,lon_lat)

    
    if xy:
        
        query = """select nodeid,  masterid, st_distance(geom, '{geom}'::geometry) as distance,
                            geom as node_geom, '{geom}'::geometry as control_geom,
                            '{xy}' as xy,  ST_AsText(st_transform(geom::text,4326)) node_lon_lat,
                            ST_AsText(st_transform('{geom}'::text,4326)) control_lon_lat
               from node where st_dwithin('{geom}'::geometry,geom, {rad})
                        and is_int = true
               order by st_distance(geom, '{geom}'::geometry) ASC limit 1
               """.format(geom=geom, rad=rad, xy=xy)
        
        r = db.query(query)[0][0]
        x=list(r[0:7])
        x.append(coor(r[4]))
        
        data=x
        #data = pd.DataFrame(x,index=['nodeid','distance','node_geom','control_geom','xy']).T
        
    elif lon_lat:

        query = """
                   select *, ST_AsText(st_transform(node_geom::text,4326)) node_lon_lat, ST_AsText(st_transform('{geom}'::text,4326)) control_lon_lat
                   from(
                   select nodeid,  masterid, st_distance(geom, '{geom}'::geometry) as distance,
                                geom as node_geom,
                                '{geom}'::geometry as sig_geom  
                   from node where st_dwithin('{geom}'::geometry,geom, {rad})
                            and is_int = true 
                   order by st_distance(geom, '{geom}'::geometry) ASC limit 1) x 
                   """.format(geom=geom, rad=rad, lon_lat=lon_lat)

        r = db.query(query)[0][0]
        x=list(r[0:7])
        #x.append(coor(r[4]))

        data=x
        #data = pd.DataFrame(x,index=['nodeid','distance','node_geom','control_geom','lon_lat']).T     
            
    else:
        
        query = """select nodeid, masterid, st_distance(geom, '{geom}'::geometry) as distance,
                                geom as node_geom, '{geom}'::geometry as control_geom,
                                ST_AsText(st_transform(geom::text,4326)) node_lon_lat,
                                ST_AsText(st_transform('{geom}'::text,4326)) control_lon_lat
                   from node where st_dwithin('{geom}'::geometry,geom, {rad})
                            and is_int = true
                   order by st_distance(geom, '{geom}'::geometry) ASC limit 1
                   """.format(geom=geom, rad=rad)
            
        r = list(db.query(query)[0][0])
        data = pd.DataFrame(r,index=['nodeid','distance','node_geom','control_geom', 'node_lon_lat', 'control_lon_lat']).T
    


    return data

In [52]:
def st_names(nodes,cdb):
    
    result = cdb.query("""    
                        select nodeid::int, array_agg(street) from(
                        select distinct nodeidto nodeid, street
                        from lion 
                        where nodeidto::int in {nodes}

                        union

                        select distinct nodeidfrom nodeid, street
                        from lion 
                        where nodeidfrom::int in {nodes}
                        ) st_names
                        group by nodeid
                        """.format(nodes=nodes))
    
    return pd.DataFrame(result.data, columns = ["nodeid","st_names"])

In [53]:
def google(geom,cdb):
    
    lon_lat = geom_to_lonlat(geom,cdb)
    
    return 'https://www.google.com/maps/@{lon},{lat},19z'.format(lat = lon_lat[0], lon=lon_lat[1])

In [54]:
def all_aws(msdb,cdb,rad=50):

    """
    Function that creates dataframe of all aws x & y coordinates with nearest intersections and details

    
    Args:
        msdb param: Database Connection Function for MS SQL server
        cdb param: Database Connection Function for PostgreSQL
        rad (int,optional): Search radius for locating nearest node from all way stop. Defaults to rad = 1000.
        
    Returns:
        aws_data (List of 2 DataFrames): aws_data[0] - Control Signals with node matches within search radius
                                                     - Nodeid, Distance between Nodeid and All Way Stop, Nodeid Geometry, 
                                                       All Way Stop geometry, All Way Stop X&Y
                                                       
                                         aws_data[1] - Contorl Signals that don't have nodes within search radius
                                                     - control_geom,  xy
    
    e.g.
    
    Input:
    
    aws_data = all_aws(msdb,cdb,50)
    
    Returns:
    
    aws_data[0] - 
    
    nodeid   distance     node_geom                                    control_geom                             xy
    26723    0.0340567    0101000020D7080000009215F0B3882E4100EA8...   0101000020D708000000000000B4882E4100...  [1000538.0, 186727.0]
    44332    0.370932     0101000020D7080000000C4B64BD962E4100200...   0101000020D708000000000000BE962E4100...  [1002335.0, 250598.0]
    27734    0.449713     0101000020D708000000859788F1AB2E4100728...   0101000020D708000000000000F2AB2E4100...  [1005049.0, 192440.0] 
    
    
    aws_data[1] - 
    
    control_geom                                        xy
    0101000020D7080000000000006A862E4100000000B0C1...   [1000245.0, 202806.0]
    0101000020D70800000000000064A72E41000000007830...   [1004466.0, 255503.0]
    0101000020D70800000000000002BA2E4100000000400D...   [1006849.0, 197032.0]
    
    """
    

    result = msdb.query("""    
    
                        SELECT Distinct 
                        'AWS' typ, a.[SRP_Order], a.[SRP_Seq], a.SR_Dsf, a.SR_Date_Last_Faced, a.X, a.Y
                        FROM dot55sql01.datawarehouse.dbo.STATUS_SGNS a 
                        JOIN dot55sql01.datawarehouse.dbo.STATUS_SIGNS b 
                                on SIR_KEY = SR_Mutcd_Code
                        WHERE a.SRP_Type=1
                                and b.MAIN_CATEGORY='Regulatory Sign' --remove parking Signs                                                                                 
                                and b.SUB_CATEGORY='All Way' -- ONLY ALL-WAYS (will only include locations labeled as all-ways) 
                                and x is not null and y is not null

                         """)
    

    aws_data = pd.DataFrame()
    fix = lambda x: float(str(x).strip())
    failed = pd.DataFrame()

    
    for i in result.data:
        try:
            ad1 = [i[0],str(i[1]).strip() + '-' + str(i[2]),str(i[3]).strip()]
            ad2 = to_itx(cdb,rad=50,xy=[fix(i[5]),fix(i[6])])
            ad1.extend(ad2)
            aws_data= aws_data.append(pd.DataFrame(ad1,index=['control_type','control_id', 'sr_dsf',
                                                              'nodeid','distance','node_geom',
                                                              'control_geom','xy']).T,ignore_index = True)
            
        except:
            f=[i[0],str(i[1]).strip() + '-' + str(i[2]),str(i[3]).strip(),fix(i[5]),fix(i[6])]
            f.extend([xy_to_geom(cdb,f[3::])])
            failed=failed.append(pd.DataFrame(f, index = ['control_type','control_id', 'SR_DSF',
                                                          'control_geom','xy','geom']).T,ignore_index = True)    
    
    aws_data['gmaps']= map(lambda x: google(x,cdb), aws_data['control_geom'])
    
    return [aws_data, failed]

In [55]:
def given_aws(cdb):
    
    result = cdb.query("""
                    select *, ST_AsText(st_transform(node_geom::text,4326)), ST_AsText(st_transform(control_geom::text,4326)), st_distance(node_geom, control_geom) from (
                    SELECT distinct 'AWS' control_type, "Order No.", " Sequence No. ", "Last Work Date", "From Node ID" nodeid, masterid, 
                    geom node_geom, ST_GeomFROMText('POINT(' || "X Coord"::text || ' ' ||  "Y Coord"::text || ')', 2263) control_geom
                    FROM working.all_way_stops_data aws
                    left join node n
                    on (aws."From Node ID")::int = n.nodeid::int
                    WHERE "Type" = 'All Way'
                    and TRIM("From Node ID"::char) is not null
                    and TRIM("X Coord"::char) is not null
                    and TRIM("Y Coord"::char) is not null
                    ) x
                    """
                   )   
    aws=pd.DataFrame(result.data, columns=['control_type', 'order_no', 'seq_no','lwd', 'nodeid', 'masterid', 'node_geom','control_geom', 'node_lon_lat', 'control_lon_lat', 'distance'])
    aws['control_id']= aws['order_no'].map(str) + '-' + aws['seq_no'].map(str)
    aws['node_lon_lat'] = map(lambda x: map(float,x.strip('POINT()').split(' ')), aws['node_lon_lat'])
    aws['control_lon_lat'] = map(lambda x: map(float,x.strip('POINT()').split(' ')), aws['control_lon_lat'])
    aws = aws.reindex(columns=['nodeid', 'masterid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance'])
    
    return aws

In [56]:

def all_sigs(gdb,cdb,rad=50):
    
    
    """
    Function that creates dataframe of all signal longitude & latitude coordinates with nearest intersections and details

    
    Args:
        gdb param: Database Connection Function for GISGRID Database
        cdb param: Database Connection Function for PostgreSQL
        rad (int,optional): Search radius for locating nearest node from signal. Defaults to rad = 300.
        
    Returns:
        sig_data (List of 2 DataFrames): sig_data[0] - Control Signals with node matches within search radius
                                                     - Nodeid, Distance between Nodeid and Signal, Nodeid Geometry, 
                                                       Signal geometry, Signal Longitude & Latitude
                                                       
                                         sig_data[1] - Control Signals that don't have nodes within search radius
                                                     - control_geom,  xy
    
    e.g.
    
    Input:
    
    sig_data = all_sigs(gdb,cdb,50)
    
    Returns:
    
    sig_data[0] - 
    
    nodeid   distance   node_geom                                 control_geom                                  lon_lat
    92892    5.06653    0101000020D708000000853B78B7192E4100...   0101000020D7080000D5011E94BF192E41347AC3...   [-73.992476, 40.715072]
    20243    15.4098    0101000020D708000080BECDD3F5FD2D4100...   0101000020D7080000F253F6F0E1FD2D4169633F...   [-74.005343, 40.721694]
    20216    27.9408    0101000020D708000000FB62772CFE2D4100...   0101000020D708000083DE03842AFE2D41A4B226...   [-74.005212, 40.720552]
    20215    0.545153   0101000020D708000080B210CF38FE2D4100...   0101000020D7080000E5AD4DCA37FE2D412DEDC0...   [-74.005188, 40.719838]
    .....    ........     ..........................................   .......................................  .....................
    
    control_geom                                        lon_lat
    0101000020D708000017E7AB2F7B302E41B94928811651...   [-73.98198, 40.713441]
    0101000020D70800008EBC932D40402E417BE2B7749798...   [-73.974688, 40.742205]
    0101000020D70800002A42A900A03C2E41F58695D20751...   [-73.976365, 40.73592]
    .................................................   .....................
    """
    
    
    """
    Function that creates a list of all signal locations in 
    the SIGNAL_CONTROLLER table of the Gisgrid database.
    
    Args:
        gdb param: Database Connection Function for GISGRID Database
        
    Returns:
        sig_data (list): List containing latitudes and longitues for all sgignals retrieved.
    
    e.g.
    
    Returns [[lat, lon]]:
    
    [[-73.992476, 40.715072],
     [-74.005343, 40.721694],
     [-74.005212, 40.720552],
     .......................]]  
    """    
    
   
    result = gdb.query("""

                    SELECT 'SIG' typ, [PSGM_ID], [Longitude] lon, [Latitude] lat
                    FROM [GISGRID].[gisadmin].[SIGNAL_CONTROLLER]
                    where NormalizedType != 'Z'
                    and [Longitude] is not null
                    
                        """)
    
  
    sig_data = pd.DataFrame()
    failed_data = pd.DataFrame()

    for i in result.data:

        try:
            s1 = [i[0],i[1]]
            s2 = to_itx(cdb,rad=50,lon_lat=[float(i[2]),float(i[3])])        
            s1.extend(s2)
            sig_data = sig_data.append(pd.DataFrame(s1,['control_type','control_id','nodeid','masterid','distance','node_geom',
                                                        'control_geom','node_lon_lat','control_lon_lat']).T, ignore_index = True)
        except:
            f = [i[0],i[1]]
            f1=lon_lat_to_geom(cdb,[float(i[2]),float(i[3])])
            f.extend([f1])
            failed_data=failed_data.append(pd.DataFrame(f,index = ['control_type','control_id','contol_geom']).T,ignore_index=True)
    
    sig_data['node_lon_lat'] = map(lambda x: map(float,x.strip('POINT()').split(' ')), sig_data['node_lon_lat'])
    sig_data['control_lon_lat'] = map(lambda x: map(float,x.strip('POINT()').split(' ')), sig_data['control_lon_lat'])
    sig_data = sig_data.reindex(columns=['nodeid', 'masterid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance'])
    return [sig_data, failed_data]

In [57]:
@db2.timeDec
def has_control(df,column):
    
    """    
    Function that filters down control tables to one control
    per node. 
   
    Args:
        df (dataFrame): Dataframe containing all data for node matched to control signals
        
    Returns:
        df (dataFrame): Dataframe containing one to one data for node matched to control signals. 
            
    e.g.
    
    Input:
    
    control = has_control(all_aws(msdb,cdb,50)[0],'nodeid')
    
    Returns:
    
    control_type    control_id      sr_dsf   nodeid   distance   node_geom    control_geom   xy
    AWS             C-399142-4      N        724      21.847148  0101000....  0101000....    [925593.0, 128793.0]
    AWS             C-01275235-4    N        910       0.192036  0101000....  0101000....    [921705.0, 134970.0]
    AWS             C-399505-8      S        967      30.546254  0101000....  0101000....    [922068.0, 135049.0]
    ...             ..........      ..       ...      .........  ...........  ...........    ....................

    Input:
    
    control = has_control(sig_lon_lat_itx(gdb,cdb,50)[0],'nodeid')
    
    control_type    control_id   nodeid   distance   node_geom    control_geom   lon_lat
    SIG             50460        51       12.562571  010100....   010100....     [-74.25183, 40.502775]
    SIG             50266        129       0.649048  010100....   010100....     [-74.246901, 40.509044]
    SIG             50274        193       0.647779  010100....   010100....     [-74.24374, 40.509993]
    ...             .....        ..       .........  ..........   ..........     ........................
    """  
    
    data_dict = {}

    for i in df[column]:

        try:
            data_dict[i]
        except:
            data_dict[i] = df.loc[df.nodeid==i].iloc[0]

    data=pd.DataFrame.from_dict(data_dict,orient='index')
    data=data.reset_index(drop=True)
    
    return data

In [58]:
def run(cdb,gdb,msdb):
    
    """
    Function that exports necessary control tables to excel for quicker processing. 
    Writes out all single aws control signals matched to nodes and all single signal
    control signals matched to nodes.
    
    Args: None

    Returns: "Complete"
    
    """    
    
    aws_control = has_control(all_aws(msdb,cdb,50)[0],'nodeid')
    sig_control = has_control(all_sigs(gdb,cdb,50)[0],'nodeid')
    
    aws_control.to_csv('solo_aws_{}.csv'.format(ts),index=False)
    sig_control.to_csv('solo_sigs_{}.csv'.format(ts),index=False)
    
    return ['solo_aws_{}.csv'.format(ts), 'solo_sigs_{}.csv'.format(ts)]

In [59]:
def tbl_check(nodes,tbl):

    """
    Function that displays boolean of wether input nodes have a control signal
    
    Args: 

        nodes (int): Nodes 
        tbl (dataFrame): Table containing all node matched to control signal information

    Returns: 

        None: If no nodes are passed
        query (dict): Dictionary of node:boolean        
    """    

    query = {}
    df = tbl['nodeid']
    
    if len(nodes)==0:
        return
 
    for i in nodes:
        if any(df.isin([i])):
            query[i] = True 
        else:
            query[i] = False

    return query

In [60]:
def details(nodes,tbl):

    """
    Function that returns details of input nodes that do have a control signal

    Args: None

    Returns: 

        dtl (dict): Dictionary of node:[dist, node_geom, control_geom, xy]

    """     

    check = tbl_check(nodes,tbl)

    dtl = {i[0]:list(tbl.loc[tbl['nodeid']==i[0]].values[0]) for i in (filter(lambda elem: elem[1] == True, check.items()))}

    return dtl

In [61]:
def g_run(cdb,gdb,msdb):
    
    """
    Function that exports necessary control tables to excel for quicker processing. 
    Writes out all single aws control signals matched to nodes and all single signal
    control signals matched to nodes.
    
    Args: None

    Returns: "Complete"
    
    """    
    
    g_aws_control = has_control(given_aws(cdb),'nodeid')
    g_sig_control = has_control(all_sigs(gdb,cdb,50)[0],'nodeid')
    
    
    g_aws_control.to_csv('g_solo_aws_{}.csv'.format(ts),index=False)
    g_sig_control.to_csv('g_solo_sigs_{}.csv'.format(ts),index=False)
    
    
    return ['g_solo_aws_{}.csv'.format(ts), 'g_solo_sigs_{}.csv'.format(ts)]

In [62]:
def google(geom,cdb):
    
    lon_lat = geom_to_lonlat(geom,cdb)
    
    return 'https://www.google.com/maps/@{lon},{lat},19z'.format(lat = lon_lat[0], lon=lon_lat[1])

In [188]:
df

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
10273,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",NaN,NaN,NaN,NaN,NaN
44870,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,...",NaN,NaN,NaN,NaN,NaN
53336,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,...",NaN,NaN,NaN,NaN,NaN
53405,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-...",NaN,NaN,NaN,NaN,NaN
53407,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,...",NaN,NaN,NaN,NaN,NaN

In [ ]:
def cmids(df):
    
    mids = df.loc[df.control_type.notnull()]
    
    return mids

In [ ]:
def controlled_mids(df,mids):
    df1 = df.copy(deep=True)
    mids = cmids(df)
    mids = mids[['masterid'] + df.columns.to_list()[df.columns.to_list().index('control_type'):]]

    result = df1.loc[:, df1.columns.to_list()[:df1.columns.to_list().index('control_type')]].merge(mids)
    
    return result

In [63]:

def cmids(df):
    c = df.copy(deep=True)
    return c[['masterid', 'geom', 'st_names', 'gmaps', 'control_type','control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
            .loc[c['control_type'].notnull()==True]\
            .loc[c['masterid'].duplicated()==True]\
            .drop_duplicates(['masterid'],keep='first')

def controlled_mids(df):
    df1 = df.copy(deep=True)
    data = cmids(df1)
    for mid in data['masterid']:

        df1.loc[df1.masterid.isin([np.int64(mid)]) & df1.control_type.isnull(),\
              ['masterid', 'geom', 'st_names', 'gmaps', 'control_type',
               'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
       = data[['masterid', 'geom', 'st_names', 'gmaps', 'control_type',
               'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
              .loc[data['masterid']==np.int64(mid)].values
    return df1

In [ ]:
def controlled_mids(df):
    df1 = df.copy(deep=True)
    data = cmids(df1)
    for mid in data['masterid']:

        df1.loc[df1.masterid.isin([np.int64(mid)]) & df1.control_type.isnull(),\
              ['masterid', 'geom', 'st_names', 'gmaps', 'control_type',
               'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
       = data[['masterid', 'geom', 'st_names', 'gmaps', 'control_type',
               'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
              .loc[data['masterid']==np.int64(mid)].values
    return df1

In [98]:
#names = run(cdb,gdb,msdb)

nodes = nu.nodes(cdb)
stn = st_names(tuple(map(str,nodes.nodeid)),cdb)
nodes = nodes.merge(stn,on='nodeid',how='left')
nodes['gmaps']= map(lambda x: google(x,cdb), nodes['geom'])


#aws_data = pd.read_csv(names[0])
sig_data = pd.read_csv('g_solo_sigs_2019-11-20.csv')

#data = pd.concat([aws_data[['nodeid','control_type','control_id','gmaps']],sig_data[['nodeid','control_type','control_id','gmaps']]], ignore_index=True)
sigs = sig_data[['nodeid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]
cntrl1 = nodes.merge(sigs, how='left', on='nodeid')

'nodes' 0.83 sec

In [99]:
df = cntrl1.loc[cntrl1.masterid==105003]

In [104]:
df

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
10273,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",NaN,NaN,NaN,NaN,NaN
44870,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,...",NaN,NaN,NaN,NaN,NaN
53336,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,...",NaN,NaN,NaN,NaN,NaN
53405,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-...",NaN,NaN,NaN,NaN,NaN
53407,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,...",NaN,NaN,NaN,NaN,NaN

In [122]:
df.columns.tolist().index('control_type')

5

In [142]:
df.columns.to_list()[df.columns.to_list().index('control_type'):]

['control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']

In [119]:
df.columns.tolist()[4:]

['gmaps',
 'control_type',
 'control_id',
 'node_lon_lat',
 'control_lon_lat',
 'distance']

In [132]:
df.loc[df.control_type == 'SIG'].masterid

10200    105003
Name: masterid, dtype: int64

In [126]:
df1 = df.copy(deep=True)

In [134]:
df1.loc[df1.masterid.isin(df.loc[df.control_type == 'SIG'].masterid)  & df1.control_type.isnull()]

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10273,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",NaN,NaN,NaN,NaN,NaN
44870,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,...",NaN,NaN,NaN,NaN,NaN
53336,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,...",NaN,NaN,NaN,NaN,NaN
53405,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-...",NaN,NaN,NaN,NaN,NaN
53407,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,...",NaN,NaN,NaN,NaN,NaN

In [143]:
df.masterid.to_list()

[105003L, 105003L, 105003L, 105003L, 105003L, 105003L]

In [149]:
df1.loc[df1.masterid.isin(df.loc[df.control_type == 'SIG'].masterid)  & df1.control_type.notnull()]

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106

In [156]:
df = df.loc[df.control_type.notnull()]
df[df.columns.to_list()[df.columns.to_list().index('control_type'):]]

,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106

In [164]:
['masterid'] + [df.columns.to_list().index('control_type'):]

SyntaxError: invalid syntax (<ipython-input-164-f88b6959a5aa>, line 1)

In [174]:
list.extend?

In [175]:
['masterid'] + df.columns.to_list()[df.columns.to_list().index('control_type'):]

['masterid',
 'control_type',
 'control_id',
 'node_lon_lat',
 'control_lon_lat',
 'distance']

In [176]:
df[['masterid'] + df.columns.to_list()[df.columns.to_list().index('control_type'):]]

,masterid,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,105003,SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
10273,105003,NaN,NaN,NaN,NaN,NaN
44870,105003,NaN,NaN,NaN,NaN,NaN
53336,105003,NaN,NaN,NaN,NaN,NaN
53405,105003,NaN,NaN,NaN,NaN,NaN
53407,105003,NaN,NaN,NaN,NaN,NaN

In [158]:
df = df1

In [177]:
mids = df.loc[df.control_type.notnull()]

In [184]:
df1

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10200,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
10273,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",NaN,NaN,NaN,NaN,NaN
44870,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,...",NaN,NaN,NaN,NaN,NaN
53336,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,...",NaN,NaN,NaN,NaN,NaN
53405,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-...",NaN,NaN,NaN,NaN,NaN
53407,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,...",NaN,NaN,NaN,NaN,NaN

In [192]:
df1.columns.to_list()[:df1.columns.to_list().index('control_type')]

['nodeid', 'masterid', 'geom', 'st_names', 'gmaps']

In [185]:
df1.loc[:, df1.columns.to_list()[:df1.columns.to_list().index('control_type')]]

,nodeid,masterid,geom,st_names,gmaps
10200,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,..."
10273,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,..."
44870,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,..."
53336,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,..."
53405,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-..."
53407,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,..."

In [187]:
df1 = df.copy(deep=True)
mids = df.loc[df.control_type.notnull()]
mids= mids[['masterid'] + df.columns.to_list()[df.columns.to_list().index('control_type'):]]

df1.loc[:, df1.columns.to_list()[:df1.columns.to_list().index('control_type')]].merge(mids)

,nodeid,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
0,15883,105003,0101000020D7080000003D51D403262E4100D8B4824DB7...,"[HOUSTON/ESSEX STREET LINE, JAY STREET, JAY ST...","https://www.google.com/maps/@40.6999343307564,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
1,16000,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
2,71489,105003,0101000020D7080000809BFD6F97272E4100CEF91FFFB6...,"[BQE EASTBOUND ENTRANCE SANDS ST, SANDS STREET]","https://www.google.com/maps/@40.6999073512911,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
3,104337,105003,0101000020D70800008091CDA744272E41003A300FEBB6...,"[JAY STREET, PEDESTRIAN AND BIKE PATH LINK, SA...","https://www.google.com/maps/@40.6999004848236,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
4,105001,105003,0101000020D7080000003FCBB7C4252E410036A10044BA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.700194579106,-...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106
5,105003,105003,0101000020D7080000006825E7E6252E4100288384DEB8...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7000719205507,...",SIG,33783.0,"[-73.9868151320701, 40.6999343307564]","[-73.986811, 40.6999539999998]",7.257106

In [112]:
df[['masterid', 'geom', 'st_names', 'gmaps', 'control_type','control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
        .loc[df['masterid'].duplicated()==True]\
        .drop_duplicates(['masterid'],keep='first')

,masterid,geom,st_names,gmaps,control_type,control_id,node_lon_lat,control_lon_lat,distance
10273,105003,0101000020D708000000B3F7E1F0262E4100DAA85E8DBA...,"[JAY STREET, SANDS STREET]","https://www.google.com/maps/@40.7002196883764,...",NaN,NaN,NaN,NaN,NaN

In [113]:
cmids(df)

Empty DataFrame
Columns: [masterid, geom, st_names, gmaps, control_type, control_id, node_lon_lat, control_lon_lat, distance]
Index: []

In [ ]:
cntrl2= controlled_mids(cntrl1)

In [20]:
def control(cdb,gdb,msdb):
    
    names = run(cdb,gdb,msdb)

    nodes = nu.nodes(cdb)
    nodes= pd.DataFrame(nodes.items(),  columns=['nodeid', 'masterid'])

    aws_data = pd.read_csv(names[0])
    sig_data = pd.read_csv(names[1])
    
    data = pd.concat([aws_data[['nodeid','control_type','control_id','gmaps']],sig_data[['nodeid','control_type','control_id','gmaps']]], ignore_index=True)
    cntrl1 = nodes.merge(data, how='left', on='nodeid')
    cntrl2= controlled_mids(cntrl1)
    
    nodes = tuple(cntrl2.loc[cntrl2.control_type.notnull()].nodeid.unique())
    stn = st_names(nodes,cdb)
    
    cntrl_final = cntrl2.merge(stn, on='nodeid', how='left')
    cntrl_final = cntrl_final.reindex(columns=['nodeid','control_type','control_id','st_names','gmaps'])
    cntrl_final.to_csv('g_raw_cntrl_data_{}.csv'.format(ts),index=False)
    
    return cntrl_final

In [333]:
def given_control(cdb,gdb,msdb):
    
    names = g_run(cdb,gdb,msdb)

    nodes = nu.nodes(cdb)
    stn = st_names(tuple(map(str,nodes.nodeid)),cdb)
    nodes = nodes.merge(stn,on='nodeid',how='left')
    nodes['gmaps']= map(lambda x: google(x,cdb), nodes['geom'])

    aws_data = pd.read_csv(names[0])
    sig_data = pd.read_csv(names[1])
    
    data = pd.concat([aws_data[['nodeid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]\
                 ,sig_data[['nodeid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance']]], ignore_index=True)
    cntrl = nodes.merge(data, how='left', on='nodeid')
    cntrlf = controlled_mids(cntrl)

    cntrlf = cntrlf.reindex(columns=['nodeid', 'masterid','control_type', 'control_id', 'node_lon_lat', 'control_lon_lat', 'distance', 'st_names','gmaps'])
    cntrlf.to_csv('g_raw_cntrl_data_{}.csv'.format(ts),index=False)
    uncntrl = cntrlf.loc[cntrlf.control_type.isnull()]
    uncntrl.to_csv('g_raw_uncntrl_data_{}.csv'.format(ts),index=False)
    
    return cntrlf

In [339]:
ts = datetime.datetime.now().strftime('%Y-%m-%d')

In [336]:
uncntrl = x

In [340]:
uncntrl = cntrlf.loc[cntrlf.control_type.isnull()]
uncntrl.to_csv('g_raw_uncntrl_data_{}.csv'.format(ts),index=False)

In [334]:
x.loc[x.control_type.isnull()]

,nodeid,masterid,control_type,control_id,node_lon_lat,control_lon_lat,distance,st_names,gmaps
1,14,14,NaN,NaN,NaN,NaN,NaN,"[PERTH AMBOY PLACE, WARDS POINT AVENUE]","https://www.google.com/maps/@40.5061652862454,..."
2,18,18,NaN,NaN,NaN,NaN,NaN,"[SATTERLEE STREET, SHORE ROAD]","https://www.google.com/maps/@40.5055137335391,..."
3,19,19,NaN,NaN,NaN,NaN,NaN,"[PERTH AMBOY PLACE, SATTERLEE STREET]","https://www.google.com/maps/@40.5062981899294,..."
4,22,22,NaN,NaN,NaN,NaN,NaN,"[TOTTENVILLE PLACE, WARDS POINT AVENUE]","https://www.google.com/maps/@40.5069564884578,..."
5,23,23,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, AVIVA COURT, WARDS POINT AVENUE]","https://www.google.com/maps/@40.5077303996471,..."
6,25,25,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, HOPPING AVENUE]","https://www.google.com/maps/@40.5076818808786,..."
7,26,26,NaN,NaN,NaN,NaN,NaN,"[SATTERLEE STREET, TOTTENVILLE PLACE]","https://www.google.com/maps/@40.5068824968805,..."
8,27,27,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, SATTERLEE STREET]","https://www.google.com/maps/@40.5076255555476,..."
11,9044003,9044003,NaN,NaN,NaN,NaN,NaN,"[BISHOP PATRICK AHERN HS DRIVEWAY, MERRILL AVE...","https://www.google.com/maps/@40.6103111756023,..."
12,9044004,9044004,NaN,NaN,NaN,NaN,NaN,"[ARLENE STREET, BISHOP PATRICK AHERN HS DRIVEWAY]","https://www.google.com/maps/@40.6092692332451,..."
13,47,47,NaN,NaN,NaN,NaN,NaN,"[CLERMONT AVENUE, MASSACHUSETTS ST SOUTH]","https://www.google.com/maps/@40.5005802173598,..."
15,52,52,NaN,NaN,NaN,NaN,NaN,"[CRAIG AVENUE, HYLAN BOULEVARD]","https://www.google.com/maps/@40.5028790565513,..."
16,53,53,NaN,NaN,NaN,NaN,NaN,"[CRAIG AVENUE, SATTERLEE STREET]","https://www.google.com/maps/@40.502289155376,-..."
17,54,54,NaN,NaN,NaN,NaN,NaN,"[HYLAN BOULEVARD, MASSACHUSETTS STREET, MASSAC...","https://www.google.com/maps/@40.5030415985747,..."
18,55,55,NaN,NaN,NaN,NaN,NaN,"[CONNECTICUT STREET, HYLAN BOULEVARD]","https://www.google.com/maps/@40.5032120794888,..."
19,56,56,NaN,NaN,NaN,NaN,NaN,"[CRAIG AVENUE, SHORE ROAD]","https://www.google.com/maps/@40.505639450852,-..."
20,57,57,NaN,NaN,NaN,NaN,NaN,"[BRYAN STREET, SHORE ROAD]","https://www.google.com/maps/@40.5057594482582,..."
21,59,59,NaN,NaN,NaN,NaN,NaN,"[CONNECTICUT STREET, SHORE ROAD]","https://www.google.com/maps/@40.5058837889201,..."
22,62,62,NaN,NaN,NaN,NaN,NaN,"[FINLAY STREET, SHORE ROAD]","https://www.google.com/maps/@40.5060031897089,..."
23,63,63,NaN,NaN,NaN,NaN,NaN,"[CRAIG AVENUE, SUMMIT ROAD]","https://www.google.com/maps/@40.5068981639091,..."
24,64,64,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, CRAIG AVENUE]","https://www.google.com/maps/@40.5075829849887,..."
25,65,65,NaN,NaN,NaN,NaN,NaN,"[BRYAN STREET, SUMMIT ROAD]","https://www.google.com/maps/@40.5068846549637,..."
26,66,66,NaN,NaN,NaN,NaN,NaN,"[CONNECTICUT STREET, SUMMIT ROAD]","https://www.google.com/maps/@40.5071229841345,..."
27,67,67,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, CONNECTICUT STREET]","https://www.google.com/maps/@40.5077827668653,..."
28,68,68,NaN,NaN,NaN,NaN,NaN,"[CRAIG AVENUE, PATTEN STREET]","https://www.google.com/maps/@40.5089382046741,..."
29,69,69,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, FINLAY STREET]","https://www.google.com/maps/@40.5080312506758,..."
30,70,70,NaN,NaN,NaN,NaN,NaN,"[FINLAY STREET, SUMMIT ROAD]","https://www.google.com/maps/@40.5073720725476,..."
31,71,71,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, ASPINWALL STREET]","https://www.google.com/maps/@40.5082819725588,..."
32,72,72,NaN,NaN,NaN,NaN,NaN,"[ASPINWALL STREET, SUMMIT ROAD]","https://www.google.com/maps/@40.5076356343874,..."
33,73,64781,NaN,NaN,NaN,NaN,NaN,"[AMBOY ROAD, BENTLEY STREET]","https://www.google.com/maps/@40.5084128642356,..."
...,...,...,...,...,...,...,...,...,...
54939,9043601,9043601,NaN,NaN,NaN,NaN,NaN,"[CORYLLOS LANE, SEAVIEW HOSPITAL DRIVEWAY]","https://www.google.com/maps/@40.591540356954,-..."
54940,9043608,9044263,NaN,NaN,NaN,NaN,NaN,"[BUFFALO STREET, GREAT KILLS PARK DRIVEWAY]","https://www.google.com/maps/@40.544862857281,-..."
54941,9043621,9043632,NaN,NaN,NaN,NaN,NaN,"[PROSPECT PARK DRIVEWAY, PROSPECT PARK WEST]","https://www.google.com/maps/@40.6671728849936,..."
54942,9043632,9043632,NaN,NaN,NaN,NaN,NaN,"[PROSPECT PARK DRIVEWAY, PROSPECT PARK WEST]","https://www.google.com/maps/@40.6655690764107,..."
54943,9043633,9043633,NaN,NaN,NaN,NaN,NaN,"[HOWARD AVENUE, ST JOHNS UNIVERSITY DRIVEWAY]","https://www.google.com/maps/@40.6200700264327,..."
54944,9043641,9043641,NaN,NaN,NaN,NaN,NaN,"[INDEPENDENCE AVENUE, SCHERVIER NURSING CARE C...","https://www.google.com/maps/@40.8825750461593,..."
54945,9043722,9043730,NaN,NaN,NaN,NaN,NaN,"[BARD AVENUE, RICHMOND UNIV MEDICAL CNTR DRVWY]","https://www.google.com/maps/@40.6363859080161,..."
54946,9043730,9043730,NaN,NaN,NaN,NaN,NaN,"[BARD AVENUE, RICHMOND UNIV MEDICAL CNTR DRVWY]","https://www.google.com/maps/@40.6350594548885,..."
54947,9048463,104897,NaN,NaN,NaN,NaN,NaN,[HAMILTON AVENUE],"https://www.google.com/maps/@40.6725267764933,..."
54948,9043792,9043792,NaN,NaN,NaN,NaN,NaN,"[ST PAULS SEMINARY DRIVEWAY, VICTORY BOULEVARD]","https://www.google.com/maps/@40.6121373642468,..."
54949,9043805,9043805,NaN,NaN,NaN,NaN,NaN,"[ARBUTUS AVENUE, SANTINA DRIVE]","https://www.google.com/maps/@40.5291331017369,..."
54950,9043807,9043807,NaN,NaN,NaN,NaN,NaN,"[BUFFALO STREET, CROOKES POINT ROAD, HARBOR ROAD]","https://www.google.com/maps/@40.53566431548,-7..."
54951,9043810,9043810,NaN,NaN,NaN,NaN,NaN,"[1 AVENUE, COLLEGE OF STATEN ISLAND DRVWY]","https://www.google.com/maps/@40.5970331176287,..."
54952,9043811,9043825,NaN,NaN,NaN,NaN,NaN,"[COLLEGE OF STATEN ISLAND DRVWY, LOOP ROAD]","https://www.google.com/maps/@40.5974875584846,..."
54953,9043823,9043825,NaN,NaN,NaN,NaN,NaN,"[COLLEGE OF STATEN ISLAND DRVWY, LOOP ROAD]","https://www.google.com/maps/@40.5983963991956,..."
54954,9043825,9043825,NaN,NaN,NaN,NaN,NaN,"[COLLEGE OF STATEN ISLAND DRVWY, LOOP ROAD]","https://www.google.com/maps/@40.6007067470895,..."
54955,9052011,9052014,NaN,NaN,NaN,NaN,NaN,"[FAILE STREET, HUNTS POINT AVENUE]","https://www.google.com/maps/@40.8151583672355,..."
54956,9000261,9000261,NaN,NaN,NaN,NaN,NaN,"[CASTLETON AVENUE, HARBOR VIEW COURT]","https://www.google.com/maps/@40.6333563349801,..."
54957,9043877,9043877,NaN,NaN,NaN,NaN,NaN,"[ELTINGVILLE TRANSIT CENTER DRVWY, WAINWRIGHT ...","https://www.google.com/maps/@40.560066897411,-..."
54958,9043892,9043892,NaN,NaN,NaN,NaN,NaN,"[ARTHUR KILL ROAD, ELTINGVILLE TRANSIT CENTER ...","https://www.google.com/maps/@40.5612850298825,..."
54959,9043915,9043915,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY G-H ROW, GOETHALS ROAD NORTH]","https://www.google.com/maps/@40.6263960455557,..."
54960,9043917,9043917,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY E-F ROW, GOETHALS COMMUNIT...","https://www.google.com/maps/@40.6283688563602,..."
54961,9043918,9043918,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY E-F ROW, GOETHALS ROAD NORTH]","https://www.google.com/maps/@40.6266871512509,..."
54962,9043919,9043919,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY C-D ROW, GOETHALS COMMUNIT...","https://www.google.com/maps/@40.6283973744413,..."
54963,9043922,9043922,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY C-D ROW, GOETHALS ROAD NORTH]","https://www.google.com/maps/@40.6269740886339,..."
54964,9043923,9043923,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY A-B ROW, GOETHALS COMMUNIT...","https://www.google.com/maps/@40.6285382974715,..."
54965,9043924,9043924,NaN,NaN,NaN,NaN,NaN,"[GOETHALS COMMUNITY A-B ROW, GOETHALS ROAD NORTH]","https://www.google.com/maps/@40.62725436846,-7..."
54966,9043949,9043949,NaN,NaN,NaN,NaN,NaN,"[PORT RICHMOND WATER PLANT DRVWY, RICHMOND TER...","https://www.google.com/maps/@40.6373695226375,..."
54967,9043951,9043955,NaN,NaN,NaN,NaN,NaN,"[ALBERT EINSTEIN COLLEGE DRIVEWAY, SACKET AVENUE]","https://www.google.com/maps/@40.8500093986619,..."
54968,9043955,9043955,NaN,NaN,NaN,NaN,NaN,"[ALBERT EINSTEIN COLLEGE DRIVEWAY, SACKET AVENUE]","https://www.google.com/maps/@40.8490526191978,..."

In [22]:
def call():
    
    """
    given_control(cdb,gdb,msdb)
    
    This function will output necessary tables for complete join
    
    """