In [1]:

from ris import db2  #library designed for SQL database connection and querying
from IPython.display import clear_output
from collections import defaultdict
from collections import defaultdict, namedtuple
import datetime 
import pandas as pd
import numpy as np
import os
from sqlalchemy import create_engine

clear_output()
timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
print 'Notebook run: {}'.format(timestamp)
print os.getcwd()

Notebook run: 2020-05-29 10:59
E:\RIS\Staff Folders\Samuel\Requests\SH\PWA\Most Recent\Final

In [2]:
cdb = db2.PostgresDb('DOTDEVRHPGSQL01', 'CRASHDATA', quiet = True)

User name (CRASHDATA):soge
Password (CRASHDATA)········

In [5]:
@db2.timeDec

def nodes(cdb):
    
    """    
    Function that creates dictionary containing all real intersections nodes 
    in crash database
   
    Args:
        cdb param: Database Connection Function for PostgreSQL 
        
    Returns:
        itx (dict): Dictionary Containing all nodes initialized to master nodes
    """
    
    itx = {}
    result = (cdb.query("""SELECT distinct nodeid, masterid, is_int, is_cntrln_int
                           FROM archive."18d.2019-11-13_node"
                           WHERE is_int = true"""))

    for i in result.data:
        
        itx[int(i[0])]=[int(i[0]),int(i[1]),i[2],i[3]]

    itx = pd.DataFrame(itx.values(),  columns=['nodeid', 'masterid', 'is_int', 'is_ctrln_int'])    
    
    return itx

In [6]:
y = nodes(cdb)

'nodes' 0.56 sec

In [8]:
y

        nodeid  masterid  is_int  is_ctrln_int
0      9043971   9043971    True          True
1           14        14    True          True
2           18        18    True          True
3           19        19    True          True
4           22        22    True          True
5           23        23    True          True
6           25        25    True          True
7           26        26    True          True
8           27        27    True          True
9      9043999   9044000    True          True
10     9044000   9044000    True          True
11     9044003   9044003    True          True
12     9044004   9044004    True          True
13          47        47    True          True
14          51        51    True          True
15          52        52    True          True
16          53        53    True          True
17          54        54    True          True
18          55        55    True          True
19          56        56    True          True
20          57        57    True          True
21          59        59    True          True
22          62        62    True          True
23          63        63    True          True
24          64        64    True          True
25          65        65    True          True
26          66        66    True          True
27          67        67    True          True
28          68        68    True          True
29          69        69    True          True
...        ...       ...     ...           ...
54925  9043598   9043598    True          True
54926  9043600   9043600    True          True
54927  9043601   9043601    True          True
54928  9043608   9044263    True          True
54929  9043621   9043632    True          True
54930  9043632   9043632    True          True
54931  9043633   9043633    True          True
54932  9043641   9043641    True          True
54933  9043722   9043730    True          True
54934  9043730   9043730    True          True
54935  9043792   9043792    True          True
54936  9043805   9043805    True          True
54937  9043807   9043807    True          True
54938  9043810   9043810    True          True
54939  9043811   9043825    True          True
54940  9043823   9043825    True          True
54941  9043825   9043825    True          True
54942    87365      5061    True         False
54943  9043877   9043877    True          True
54944  9043892   9043892    True          True
54945  9043915   9043915    True          True
54946  9043917   9043917    True          True
54947  9043918   9043918    True          True
54948  9043919   9043919    True          True
54949  9043922   9043922    True          True
54950  9043923   9043923    True          True
54951  9043924   9043924    True          True
54952  9043949   9043949    True          True
54953  9043951   9043955    True          True
54954  9043955   9043955    True          True

[54955 rows x 4 columns]