## Request:  Map of Street Ends

### 1. Locating all of the dead ends on LION

In [36]:
from ris import db2  #library designed for SQL database connection and querying
from IPython.display import clear_output
import datetime 
from datetime import date
import pandas as pd
import os
import decimal
from sqlalchemy import create_engine


clear_output()
timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
print 'Notebook run: {}'.format(timestamp)
print os.getcwd()
# %load_ext sql

Notebook run: 2019-07-16 17:11
C:\Users\soge\Desktop

In [4]:
#Database connections
#db = db2.PostgresDb('dotdevpgsql02', 'GISGRID', quiet = True)
cdb = db2.PostgresDb('dotdevpgsql02', 'CRASHDATA', quiet = True)

User name (CRASHDATA):soge
Password (CRASHDATA)········

In [ ]:
##

In [5]:
nfrom =  cdb.query("""--nodes1
                        select distinct n.nodeid,l.geom 
                        from node n
                        join lion l on
                        n.nodeid = l.nodeidfrom::int
                        --where nodeid = 25438
                        and l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
                        and n.vintersect is null""")

In [6]:
nfrom = pd.DataFrame(nfrom.data, columns =['nodeid','geom'])

In [7]:
nfrom

         nodeid                                               geom
0            10  0105000020D70800000100000001020000000200000000...
1            10  0105000020D70800000100000001020000000200000000...
2            11  0105000020D70800000100000001020000000200000000...
3            11  0105000020D70800000100000001020000000200000000...
4            14  0105000020D70800000100000001020000000200000000...
5            17  0105000020D70800000100000001020000000400000080...
6            18  0105000020D70800000100000001020000000200000080...
7            18  0105000020D70800000100000001020000000200000080...
8            19  0105000020D70800000100000001020000000200000000...
9            19  0105000020D70800000100000001020000000200000000...
10           22  0105000020D70800000100000001020000000200000080...
11           23  0105000020D70800000100000001020000000200000000...
12           23  0105000020D70800000100000001020000000200000000...
13           23  0105000020D70800000100000001020000000200000000...
14           24  0105000020D70800000100000001020000000200000000...
15           25  0105000020D70800000100000001020000000200000000...
16           26  0105000020D70800000100000001020000000200000000...
17           26  0105000020D70800000100000001020000000200000000...
18           27  0105000020D70800000100000001020000000200000000...
19           27  0105000020D70800000100000001020000000200000000...
20           31  0105000020D70800000100000001020000000200000080...
21           37  0105000020D70800000100000001020000000200000080...
22           42  0105000020D70800000100000001020000000200000080...
23           43  0105000020D70800000100000001020000000200000000...
24           44  0105000020D70800000100000001020000000200000000...
25           46  0105000020D70800000100000001020000000200000080...
26           46  0105000020D70800000100000001020000000200000080...
27           47  0105000020D70800000100000001020000000200000080...
28           48  0105000020D70800000100000001020000000200000000...
29           49  0105000020D70800000100000001020000000200000080...
...         ...                                                ...
155192  9053391  0105000020D70800000100000001020000000200000080...
155193  9053393  0105000020D70800000100000001020000000200000000...
155194  9053393  0105000020D70800000100000001020000000200000000...
155195  9053394  0105000020D70800000100000001020000000200000080...
155196  9053394  0105000020D70800000100000001020000000200000080...
155197  9053395  0105000020D70800000100000001020000000200000080...
155198  9053396  0105000020D70800000100000001020000000200000080...
155199  9053397  0105000020D70800000100000001020000000200000000...
155200  9053400  0105000020D70800000100000001020000000200000080...
155201  9053400  0105000020D70800000100000001020000000200000080...
155202  9053401  0105000020D70800000100000001020000000200000000...
155203  9053402  0105000020D70800000100000001020000000200000080...
155204  9053404  0105000020D70800000100000001020000000500000080...
155205  9053405  0105000020D70800000100000001020000000200000080...
155206  9053405  0105000020D70800000100000001020000000900000080...
155207  9053406  0105000020D70800000100000001020000000900000080...
155208  9053426  0105000020D70800000100000001020000000200000080...
155209  9053426  0105000020D70800000100000001020000000200000080...
155210  9053427  0105000020D70800000100000001020000000200000080...
155211  9053429  0105000020D70800000100000001020000000200000080...
155212  9053430  0105000020D70800000100000001020000000700000000...
155213  9053431  0105000020D70800000100000001020000000500000080...
155214  9053432  0105000020D70800000100000001020000000500000000...
155215  9053433  0105000020D70800000100000001020000000500000000...
155216  9053433  0105000020D70800000100000001020000000200000000...
155217  9053434  0105000020D70800000100000001020000000200000000...
155218  9053435  0105000020D70800000100000001020000000500000080...
155219  9053435  0105000020D70800000100000001020000000200000080...
155220  9053436  0105000020D70800000100000001020000000200000000...
155221  9053440  0105000020D70800000100000001020000000200000000...

[155222 rows x 2 columns]

In [9]:
nto =  cdb.query("""--nodes1
                        select distinct n.nodeid,l.geom 
                        from node n
                        join lion l on
                        n.nodeid = l.nodeidto::int
                        --where nodeid = 25438
                        and l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
                        and n.vintersect is null""")

In [10]:
nto = pd.DataFrame(nto.data, columns =['nodeid','geom'])

In [11]:
nto

         nodeid                                               geom
0             9  0105000020D70800000100000001020000000200000000...
1            10  0105000020D70800000100000001020000000200000000...
2            11  0105000020D70800000100000001020000000200000080...
3            13  0105000020D70800000100000001020000000200000080...
4            14  0105000020D70800000100000001020000000200000080...
5            14  0105000020D70800000100000001020000000200000000...
6            16  0105000020D70800000100000001020000000200000000...
7            17  0105000020D70800000100000001020000000300000000...
8            18  0105000020D70800000100000001020000000200000080...
9            18  0105000020D70800000100000001020000000200000080...
10           19  0105000020D70800000100000001020000000200000000...
11           21  0105000020D70800000100000001020000000200000000...
12           22  0105000020D70800000100000001020000000200000000...
13           22  0105000020D70800000100000001020000000200000000...
14           23  0105000020D70800000100000001020000000200000000...
15           24  0105000020D70800000100000001020000000200000080...
16           25  0105000020D70800000100000001020000000200000000...
17           25  0105000020D70800000100000001020000000200000000...
18           26  0105000020D70800000100000001020000000200000000...
19           27  0105000020D70800000100000001020000000200000080...
20           30  0105000020D70800000100000001020000000200000080...
21           31  0105000020D70800000100000001020000000200000000...
22           37  0105000020D70800000100000001020000000200000080...
23           37  0105000020D70800000100000001020000000200000080...
24           38  0105000020D70800000100000001020000000200000080...
25           38  0105000020D70800000100000001020000000200000080...
26           41  0105000020D70800000100000001020000000200000000...
27           41  0105000020D70800000100000001020000000200000000...
28           42  0105000020D70800000100000001020000000200000000...
29           42  0105000020D70800000100000001020000000200000000...
...         ...                                                ...
155180  9053391  0105000020D70800000100000001020000000200000000...
155181  9053393  0105000020D70800000100000001020000000200000000...
155182  9053393  0105000020D70800000100000001020000000200000080...
155183  9053394  0105000020D70800000100000001020000000200000080...
155184  9053395  0105000020D70800000100000001020000000200000080...
155185  9053396  0105000020D70800000100000001020000000200000000...
155186  9053397  0105000020D70800000100000001020000000200000000...
155187  9053400  0105000020D70800000100000001020000000200000000...
155188  9053401  0105000020D70800000100000001020000000200000080...
155189  9053402  0105000020D70800000100000001020000000200000080...
155190  9053404  0105000020D70800000100000001020000000200000080...
155191  9053404  0105000020D70800000100000001020000000200000080...
155192  9053406  0105000020D70800000100000001020000000900000080...
155193  9053406  0105000020D70800000100000001020000000200000000...
155194  9053426  0105000020D70800000100000001020000000200000000...
155195  9053427  0105000020D70800000100000001020000000200000080...
155196  9053429  0105000020D70800000100000001020000000200000080...
155197  9053430  0105000020D70800000100000001020000000200000080...
155198  9053430  0105000020D70800000100000001020000000500000080...
155199  9053431  0105000020D70800000100000001020000000500000000...
155200  9053432  0105000020D70800000100000001020000000200000080...
155201  9053432  0105000020D70800000100000001020000000500000080...
155202  9053433  0105000020D70800000100000001020000000700000000...
155203  9053434  0105000020D70800000100000001020000000200000000...
155204  9053435  0105000020D70800000100000001020000000900000080...
155205  9053436  0105000020D70800000100000001020000000200000080...
155206  9053440  0105000020D70800000100000001020000000200000080...
155207  9053440  0105000020D70800000100000001020000000B00000000...
155208  9053442  0105000020D70800000100000001020000000200000000...
155209  9053443  0105000020D70800000100000001020000000200000000...

[155210 rows x 2 columns]

In [12]:
nodes = db2.query_to_table(cdb,"""select nodeid,geom from node""")

In [13]:
nodes

         nodeid                                               geom
0       9008720  0101000020D70800008021867E01D92E41006ED2DF9B72...
1       9008722  0101000020D708000000BDD0EA39EC2E4100D2A79B60D9...
2       9008727  0101000020D7080000001A538AD1002F4100B861E59152...
3       9008728  0101000020D7080000803B9C60EAEB2E410002BD4741D3...
4       9008729  0101000020D708000000B24CEF62F52E41001687A0B104...
5       9008730  0101000020D708000080BBB3C178FD2E4100A0029A4C26...
6       9008734  0101000020D7080000807ECEFE464F2F41006AEE5F4E28...
7       9008742  0101000020D708000000C716C97C472F41006E6BC69B1B...
8       9008748  0101000020D708000000357ED1AFA52E41006270EA8BD7...
9       9008749  0101000020D708000000DC69301AA82E410006640B67EB...
10      9008754  0101000020D70800008064A644C4A82E4100EEF1122FEA...
11      9008755  0101000020D7080000009BB8AD7CC72E410072B5E607F8...
12      9008758  0101000020D708000000E23CB72CC92E410034ECFC237A...
13      9008766  0101000020D70800000088B2361DFE2E41001CA53F470A...
14      9008772  0101000020D70800008004060FDAB12E4100C26C74F41B...
15      9008775  0101000020D708000080AD4B183DDC2E41006E5F90BC09...
16      9008785  0101000020D70800000002D716DAE52E41002800A14C3E...
17      9008791  0101000020D7080000009316E4D26D2D41001E0CE0E63F...
18      9008793  0101000020D7080000000DFE6D206F2D4100DE4E1BDA2A...
19      9008794  0101000020D7080000000A3FD0B4672D4100DED7D02D6B...
20      9008802  0101000020D708000000A1C341468B2C4100EE03C522A6...
21      9008806  0101000020D7080000003A0C8831122D41000047FA7930...
22      9008808  0101000020D70800000050B3BA09192D4100F26B7AF845...
23      9008811  0101000020D708000080470B73F4062D41004A67480A1B...
24      9008816  0101000020D7080000003CD6B50EF62B410044F29ED00F...
25      9008819  0101000020D708000000327B5AB20D2C4100107D5C9355...
26      9008822  0101000020D708000080D8C079DE362C41000455E2E3B3...
27      9008824  0101000020D7080000809D3523B7522C4100407ABA98DD...
28      9008837  0101000020D7080000008CD960449F2C410034982C74C3...
29      9008840  0101000020D708000000587DF865AD2C4100866B4229E9...
...         ...                                                ...
132143  9008599  0101000020D708000000AC80596F142F4100866474F31C...
132144  9008603  0101000020D7080000807023AB97F22E41001870AB8F63...
132145  9008604  0101000020D7080000001A079E29F52E41005677C6695D...
132146  9008608  0101000020D7080000001358AA44A82E4100BA6C6248F4...
132147  9008610  0101000020D708000080196C2782F62E4100C265CDF07E...
132148  9008619  0101000020D70800000061DC796F212F41007E289E9DAD...
132149  9008615  0101000020D708000000F23543191E2F41009AD7465AA8...
132150  9008620  0101000020D708000080109673FDF52E410048276E9F69...
132151   108649  0101000020D708000080DDDB75D1F22E41003C9CE42168...
132152  9008623  0101000020D708000080FC6892E7012F4100F4AB13FE7B...
132153  9008625  0101000020D7080000808F2C2C42192F410084DBF1BBA0...
132154  9008630  0101000020D70800008030133E840E2F410066CF77E28F...
132155  9008640  0101000020D708000000386F483FC22F4100946FB3E772...
132156  9008653  0101000020D7080000808163DB01D42F41005CAE4C8F77...
132157  9008657  0101000020D708000080B535CA4FCA2F4100F60FB87A73...
132158  9008662  0101000020D70800008096BF4B516D2F4100800D228F33...
132159  9008663  0101000020D7080000809D3C520A6F2F41008A6079C238...
132160  9008674  0101000020D70800004094A9391B1D304100268352A60F...
132161  9008678  0101000020D708000040E34F46B517304100A2F83237E2...
132162  9008680  0101000020D708000040EB3F891412304100B6C591E0A1...
132163  9008685  0101000020D70800000022AFBABB16304100AC3994BDC6...
132164  9008686  0101000020D708000000DAE96A3DEA2E4100BE1A1F44EA...
132165  9008692  0101000020D70800000081C555F8CB2E4100861F00AF86...
132166  9008693  0101000020D70800008096C9BE7FCA2E41003220B9078F...
132167  9008694  0101000020D7080000003DC73D82CA2E4100742590F98E...
132168  9008698  0101000020D7080000007D8326B0DC2E41002E6E43A953...
132169  9008701  0101000020D708000000E9FADC85092F4100BEAB99A601...
132170  9008702  0101000020D70800008085488BEEFF2E41008C56530905...
132171  9008708  0101000020D708000000D6DA86F91B2F4100E4B459A707...
132172  9008713  0101000020D708000080973551600D2F41006C7C93AD02...

[132173 rows x 2 columns]

In [14]:
b=pd.merge(nfrom.nodeid, nto.nodeid, how='inner')

In [31]:
b

         nodeid
0            10
1            10
2            11
3            11
4            14
5            14
6            17
7            18
8            18
9            18
10           18
11           19
12           19
13           22
14           22
15           23
16           23
17           23
18           24
19           25
20           25
21           26
22           26
23           27
24           27
25           31
26           37
27           37
28           42
29           42
...         ...
230574  9053394
230575  9053394
230576  9053395
230577  9053396
230578  9053397
230579  9053400
230580  9053400
230581  9053401
230582  9053402
230583  9053404
230584  9053404
230585  9053406
230586  9053406
230587  9053426
230588  9053426
230589  9053427
230590  9053429
230591  9053430
230592  9053430
230593  9053431
230594  9053432
230595  9053432
230596  9053433
230597  9053433
230598  9053434
230599  9053435
230600  9053435
230601  9053436
230602  9053440
230603  9053440

[230604 rows x 1 columns]

In [15]:
c = set([ int(i) for i in set(b.nodeid)])

In [16]:
a= set([ int(i) for i in set(nodes.nodeid)])

In [17]:
d= a^c

In [18]:
d

{1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 12,
 13,
 15,
 16,
 20,
 21,
 28,
 30,
 32,
 33,
 34,
 36,
 38,
 39,
 40,
 43,
 45,
 58,
 60,
 61,
 86,
 88,
 90,
 91,
 92,
 100,
 101,
 103,
 105,
 106,
 108,
 109,
 110,
 111,
 122,
 134,
 140,
 143,
 151,
 152,
 153,
 154,
 156,
 157,
 158,
 159,
 160,
 162,
 163,
 164,
 182,
 187,
 189,
 202,
 206,
 207,
 210,
 35,
 212,
 213,
 214,
 215,
 216,
 217,
 220,
 41,
 252,
 265,
 268,
 283,
 284,
 288,
 289,
 312,
 318,
 320,
 324,
 338,
 342,
 349,
 355,
 363,
 366,
 373,
 378,
 379,
 381,
 382,
 384,
 387,
 392,
 393,
 397,
 399,
 87448,
 402,
 414,
 421,
 422,
 425,
 426,
 427,
 428,
 429,
 430,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 440,
 441,
 442,
 444,
 451,
 454,
 459,
 466,
 9000355,
 470,
 472,
 479,
 484,
 489,
 490,
 491,
 500,
 507,
 517,
 519,
 522,
 523,
 525,
 526,
 527,
 530,
 531,
 89,
 9000367,
 546,
 577,
 580,
 584,
 586,
 589,
 596,
 601,
 607,
 613,
 615,
 616,
 61124,
 630,
 639,
 640,
 646,
 648,
 653,
 655,
 87491,
 662,
 668,
 669,
 674,
 683,
 684,
 690,
 691,
 706,
 708,
 709,
 710,
 712,
 717,
 718,
 728,
 730,
 733,
 734,
 740,
 741,
 750,
 753,
 758,
 761,
 762,
 764,
 766,
 775,
 776,
 782,
 793,
 794,
 801,
 804,
 810,
 811,
 813,
 87517,
 822,
 824,
 825,
 826,
 835,
 840,
 844,
 9008398,
 858,
 9044111,
 861,
 868,
 882,
 883,
 884,
 885,
 886,
 887,
 891,
 892,
 898,
 903,
 908,
 909,
 913,
 916,
 928,
 938,
 946,
 9000435,
 948,
 958,
 962,
 87542,
 976,
 977,
 989,
 992,
 1003,
 1006,
 1010,
 1024,
 1026,
 1030,
 1033,
 1034,
 1035,
 1056,
 1058,
 1061,
 1076,
 1077,
 1088,
 1089,
 9000459,
 1112,
 1114,
 1116,
 1118,
 1130,
 1138,
 1140,
 1147,
 1153,
 1159,
 1160,
 1179,
 1180,
 1186,
 9000475,
 1188,
 1190,
 1191,
 9000476,
 1194,
 1196,
 1201,
 1203,
 1215,
 1216,
 1227,
 1230,
 1245,
 1254,
 1258,
 1263,
 1269,
 1274,
 1297,
 1309,
 1312,
 87600,
 1315,
 1339,
 1366,
 43691,
 1396,
 1402,
 1424,
 1438,
 1447,
 1452,
 52423,
 17507,
 1491,
 1492,
 1495,
 1515,
 1516,
 87635,
 1527,
 87643,
 1578,
 1582,
 1584,
 1585,
 1586,
 1587,
 1588,
 1593,
 1599,
 1600,
 1601,
 1604,
 1605,
 1614,
 1616,
 1618,
 1621,
 1624,
 1629,
 1630,
 1641,
 1648,
 1650,
 275,
 1652,
 1659,
 1660,
 1662,
 1663,
 1664,
 1674,
 1679,
 1683,
 87662,
 1687,
 1699,
 1700,
 1707,
 1710,
 1711,
 1715,
 1716,
 1717,
 1718,
 1719,
 1722,
 1723,
 1727,
 1730,
 9044257,
 1738,
 87671,
 1740,
 1745,
 1748,
 1752,
 1753,
 1754,
 1755,
 1756,
 1757,
 1758,
 1759,
 1760,
 1761,
 1762,
 1763,
 1764,
 1766,
 1767,
 1768,
 1771,
 1772,
 1773,
 1774,
 1775,
 1776,
 1777,
 1778,
 1780,
 1782,
 1783,
 1784,
 1786,
 1788,
 1789,
 1794,
 1796,
 1797,
 1798,
 1800,
 1801,
 1802,
 1803,
 1804,
 1806,
 1807,
 1808,
 1811,
 1813,
 1814,
 1815,
 1816,
 1818,
 1819,
 1820,
 1821,
 1822,
 1823,
 1824,
 1825,
 1826,
 1827,
 1828,
 1829,
 1830,
 1831,
 1832,
 1836,
 1838,
 1839,
 1840,
 9000584,
 1842,
 1843,
 1844,
 1845,
 1846,
 1848,
 1849,
 1850,
 1851,
 1852,
 1854,
 1855,
 1856,
 1857,
 1862,
 1863,
 1864,
 1865,
 1866,
 1867,
 1869,
 1870,
 1872,
 1873,
 1884,
 1888,
 9000593,
 1897,
 1900,
 1903,
 1906,
 1911,
 1913,
 1915,
 1916,
 1917,
 1918,
 1927,
 1928,
 1929,
 1931,
 1939,
 1941,
 1947,
 1950,
 1951,
 1952,
 1953,
 9008436,
 2008,
 2014,
 2022,
 2054,
 2055,
 2060,
 2102,
 87732,
 2108,
 2110,
 2112,
 2116,
 2118,
 2132,
 2146,
 2160,
 2161,
 87743,
 2176,
 2187,
 2188,
 9000646,
 2219,
 2223,
 2239,
 2244,
 2245,
 2251,
 2254,
 2261,
 9008446,
 2294,
 2296,
 2299,
 2304,
 2310,
 2312,
 2329,
 2330,
 2333,
 2337,
 87772,
 2349,
 2356,
 2364,
 2372,
 2398,
 2399,
 2400,
 2401,
 2402,
 2405,
 2406,
 9000680,
 9044373,
 2433,
 9008452,
 2486,
 2494,
 9008453,
 2527,
 2540,
 2541,
 9000703,
 2568,
 2616,
 2634,
 2646,
 2647,
 2663,
 2664,
 2665,
 2672,
 2706,
 2707,
 2711,
 87836,
 2730,
 2731,
 2733,
 2738,
 2745,
 2749,
 2752,
 2754,
 2755,
 2756,
 2757,
 2758,
 10493,
 2766,
 2770,
 2773,
 2774,
 2775,
 2776,
 2778,
 2779,
 2781,
 2782,
 2784,
 2785,
 2792,
 2803,
 2806,
 2809,
 2812,
 2824,
 2826,
 2827,
 2842,
 2852,
 2859,
 9008465,
 2866,
 2877,
 2878,
 2891,
 2892,
 2893,
 2894,
 2895,
 2896,
 2897,
 2916,
 2928,
 2930,
 2950,
 9008468,
 2953,
 2954,
 2955,
 2956,
 2977,
 2980,
 9044466,
 9044467,
 3000,
 3001,
 3002,
 3003,
 3004,
 3005,
 3006,
 3007,
 87884,
 3018,
 3019,
 3037,
 3038,
 3042,
 3043,
 3047,
 3048,
 3051,
 3054,
 3055,
 3056,
 3057,
 3058,
 3066,
 3085,
 3098,
 3099,
 3100,
 87899,
 64615,
 3118,
 87904,
 3141,
 3147,
 3150,
 3151,
 3152,
 3153,
 3156,
 3157,
 3158,
 3163,
 3204,
 3205,
 3219,
 3225,
 3226,
 3230,
 3232,
 3236,
 3237,
 3241,
 3242,
 3247,
 3248,
 3249,
 87926,
 3275,
 3276,
 87928,
 3286,
 3291,
 3296,
 3298,
 3299,
 3301,
 3305,
 3306,
 3308,
 3309,
 3314,
 3318,
 3321,
 3322,
 3332,
 3339,
 3340,
 3342,
 3343,
 3344,
 3345,
 3346,
 3348,
 3349,
 3350,
 3355,
 3358,
 3360,
 3362,
 3375,
 3376,
 3378,
 3380,
 3381,
 3382,
 3384,
 3385,
 3386,
 3387,
 3388,
 3390,
 3391,
 3393,
 3396,
 3400,
 3402,
 3403,
 3404,
 3405,
 3406,
 3408,
 3412,
 3414,
 3428,
 3434,
 9044543,
 3458,
 9008485,
 3470,
 3472,
 3476,
 3478,
 3489,
 3492,
 3498,
 3500,
 3507,
 3514,
 3522,
 587,
 3530,
 3533,
 3534,
 3538,
 3539,
 3540,
 3565,
 3570,
 3571,
 3578,
 9008489,
 3586,
 3590,
 3591,
 3596,
 3601,
 3605,
 3606,
 3608,
 3609,
 3610,
 3611,
 3612,
 3613,
 3614,
 3615,
 3618,
 3625,
 3626,
 3642,
 3649,
 3650,
 3658,
 3670,
 3674,
 3675,
 9044581,
 3680,
 3694,
 3697,
 3699,
 617,
 3711,
 3723,
 3727,
 3730,
 3731,
 3732,
 3733,
 3742,
 3746,
 3768,
 3772,
 3781,
 3790,
 3798,
 3802,
 3804,
 3808,
 3815,
 3818,
 3821,
 3858,
 87644,
 3899,
 3902,
 3903,
 3931,
 3937,
 3960,
 3970,
 3976,
 3982,
 3993,
 3995,
 3996,
 3997,
 3999,
 4000,
 4001,
 4002,
 4003,
 4004,
 4005,
 4006,
 4008,
 4009,
 4010,
 4014,
 4015,
 4016,
 4017,
 4021,
 4024,
 4025,
 4026,
 4028,
 4029,
 4030,
 4032,
 4033,
 4034,
 4035,
 4036,
 4045,
 4046,
 4047,
 4048,
 4050,
 4056,
 4057,
 4063,
 4065,
 4066,
 4072,
 4076,
 4082,
 4084,
 4086,
 4089,
 4090,
 4094,
 4095,
 4096,
 4098,
 4102,
 4106,
 4117,
 4120,
 4123,
 4124,
 4126,
 4128,
 4129,
 4132,
 4136,
 4140,
 4141,
 4142,
 4143,
 4144,
 4147,
 4150,
 4166,
 4184,
 4185,
 96159,
 88082,
 4207,
 4210,
 88086,
 4232,
 4233,
 4234,
 4236,
 4269,
 4274,
 4280,
 4282,
 4288,
 4290,
 4294,
 4299,
 4300,
 4301,
 4302,
 4303,
 4304,
 4305,
 4306,
 4316,
 4320,
 4321,
 4322,
 4327,
 4348,
 4352,
 4356,
 4365,
 4366,
 4368,
 4376,
 4379,
 4382,
 4400,
 4403,
 88116,
 4411,
 4414,
 4418,
 4419,
 4420,
 4421,
 4422,
 737,
 4431,
 4432,
 4433,
 4434,
 4435,
 9001017,
 4442,
 4444,
 4447,
 4448,
 4453,
 4459,
 4467,
 4477,
 4479,
 4483,
 4484,
 4485,
 4489,
 4490,
 4492,
 4493,
 4494,
 88131,
 4508,
 4512,
 4513,
 4514,
 4518,
 4520,
 4521,
 4522,
 4526,
 4527,
 4528,
 4529,
 9008521,
 4566,
 4569,
 4570,
 4573,
 9008522,
 4575,
 4576,
 ...}

In [19]:
ends=pd.DataFrame(map(decimal.Decimal, d),columns=['nodeid'])

In [26]:
len(ends)

27988

In [27]:
result = pd.concat([nodes, ends], axis=1, join='inner')

In [33]:
dead_ends = ends.merge(nodes)

In [34]:
dead_ends

        nodeid                                               geom
0            1  0101000020D708000000DF7ED2F5DA2B4100305CDC4227...
1            2  0101000020D708000080E9169A49F62B4100FC80101AFC...
2            3  0101000020D7080000809C49233ED72B41007847B54969...
3            4  0101000020D70800008052A42648D72B410034F61E45EA...
4            5  0101000020D7080000009629F3DCD72B41000458FC4365...
5            6  0101000020D708000000B28FB296D82B4100881D2D6476...
6            7  0101000020D70800008047B11F00D92B4100E8B2D90C5E...
7            8  0101000020D70800008082C6B314E12B410084C42624DD...
8            9  0101000020D708000000E967DE59E12B4100748C2FD0E1...
9           12  0101000020D708000080D2AB52AADE2B410088E5783422...
10          13  0101000020D708000000070992E7E02B410000B1157125...
11          15  0101000020D7080000001F7719DEE12B41005C72AF3D17...
12          16  0101000020D7080000007B548068E12B4100DC0CAEB630...
13          20  0101000020D7080000807F283439DE2B4100F09211425D...
14          21  0101000020D7080000009F6248F5DE2B4100443908D65C...
15          28  0101000020D70800000028D2F73AE22B4100F0CE49E981...
16          30  0101000020D7080000003FA3DB75E42B4100308A80B89D...
17          32  0101000020D7080000800DA7E5AEE32B4100747BA3CFC0...
18          33  0101000020D7080000009FFD5E82E42B4100B0AD5CB2C2...
19          34  0101000020D708000080A2C8F6F0DF2B4100787123D509...
20          36  0101000020D708000080C81D3164E82B410068A8D4DA7E...
21          38  0101000020D70800000083BF7C97EA2B410080DEE7E27B...
22          39  0101000020D708000000B0DEE953EC2B4100D0A6B5795C...
23          40  0101000020D708000000B1F6079DE42B4100B48FEE36A4...
24          43  0101000020D708000000658C2A43E72B4100185430D9AE...
25          45  0101000020D7080000004DA3B4F1EA2B4100F86DEA06B9...
26          58  0101000020D708000080D16A1B5CE72B410000CAC69727...
27          60  0101000020D708000000B9100E39E92B4100D8AF92502A...
28          61  0101000020D708000000B138443BEB2B4100D49133212D...
29          86  0101000020D708000000EEFF783DEC2B410084BF0DF2A1...
...        ...                                                ...
27958    86817  0101000020D7080000006ED5AC49F22F4100B2ADC43648...
27959     8633  0101000020D7080000803C1A39E7102D41006876FAF2C5...
27960    21647  0101000020D70800008049BA1ECB242E41001A1CC3FA52...
27961    87071  0101000020D7080000C02E794C983A3041005447217B66...
27962    95959  0101000020D70800000011436D2F6F2F41007027CF12AD...
27963    87089  0101000020D7080000002F8EAC1F802D41000279C92A5C...
27964  9000010  0101000020D70800000025914A777A2C4100F6403E0AC2...
27965  9008321  0101000020D708000000527EDFFB8B2F410000B0629CC4...
27966    11171  0101000020D7080000802C069D8E532D41001C7E92FA6E...
27967    87205  0101000020D708000080CDD78C305E2C4100C2915CC9DE...
27968    89105  0101000020D708000080F5F868A6DF2E4100D4836D6EC9...
27969    87224  0101000020D708000080F11C561DF22B4100D00EA3E2E1...
27970  9043819  0101000020D708000080C31BA74E252C4100CE38C6DB47...
27971    43547  0101000020D708000000963011289A2E410088957A5F6B...
27972  9001467  0101000020D708000000A1CCCEA63D2E41003C78C4384E...
27973    87248  0101000020D70800000059BC6CC2EE2B4100809BD69A0B...
27974    43559  0101000020D708000000D6E603CC9C2E4100B441136E9C...
27975    17435  0101000020D70800008011C02A38512E4100EE9470998A...
27976  9000184  0101000020D708000080FDA7E15B0B2D4100D02C0FE316...
27977  9000187  0101000020D708000000201D5F870B2D41007CDFC33D17...
27978  9000190  0101000020D708000000D5F679B90B2D410082D344A617...
27979    87300  0101000020D708000000AD04B827AD2C4100D0ED775D27...
27980    87302  0101000020D708000080D0A479D4B32C410094112E0936...
27981  9000204  0101000020D708000080376C4838272D4100468C6042BC...
27982    43629  0101000020D708000080A5D834139B2E41005EF97CA077...
27983    87321  0101000020D708000080F8848ABA852E4100A4A37D3BEB...
27984    87325  0101000020D708000000AF2E41B7872E410068D6609AF9...
27985    87355  0101000020D7080000007640DD7DDE2C4100E251A32E06...
27986    87378  0101000020D70800000077626A7C862C4100203AC3D699...
27987    87379  0101000020D70800000009F3B49E862C4100F8E4E22F99...

[27988 rows x 2 columns]

In [37]:
engine = create_engine('postgresql://{user}:{pw}@10.243.154.52:5432/CRASHDATA'.format(user=cdb.params['user'],
                                                                                          pw=cdb.params['password']),
                                                                                          echo=False)

dead_ends.to_sql(name='dead_ends', con= engine, if_exists = 'replace', index=False)

In [38]:
cdb.query("""ALTER TABLE dead_ends
                ALTER COLUMN geom TYPE Geometry USING geom::Geometry;
                
                grant all on dead_ends to public;""")

output(data=None, columns=None, desc=None)

In [130]:
nodes = db2.query_to_table(cdb,"""select nodeid,geom 
                                  from node 
                                  where nodeid in  (""" format(""",""".join(str(d) for node in d) """)

27988

In [ ]:
#for i in d:
#    print nodes.loc[nodes.nodeid==decimal.Decimal(i)]

In [125]:
#print nodes.loc[nodes.nodeid==decimal.Decimal(2788)]

In [128]:
e=pd.DataFrame(d)

In [39]:
test = db2.query_to_table(cdb,"""select nodeidfrom
                    from lion
                    where rb_layer in ('R', 'B', 'N') and featuretyp not in ('1', '2', '3', '7', 'A', 'F')
                    and nodeidfrom not in (select nodeidto
                    from lion
                        where rb_layer in ('R', 'B', 'N') and featuretyp not in ('1', '2', '3', '7', 'A', 'F')
                        ) 
                 """ )

Query Failed:

	select nodeidfrom
	                    from lion
	                    where rb_layer in ('R', 'B', 'N') and featuretyp not in ('1', '2', '3', '7', 'A', 'F')
	                    and nodeidfrom not in (select nodeidto
	                    from lion
	                        where rb_layer in ('R', 'B', 'N') and featuretyp not in ('1', '2', '3', '7', 'A', 'F')
	                        )

SystemExit:

C:\Python27\ArcGIS10.4\lib\site-packages\IPython\core\interactiveshell.py:2886: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [ ]:
select tot.nodeid, n2.geom from (
select coalesce(nodeidto, nodeidfrom) nodeid from (
select distinct l.nodeidfrom
from lion l
join node n on
n.nodeid = l.nodeidfrom::int
where l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
and n.vintersect is null
) f
full join
(
select distinct l.nodeidto
from lion l
join node n on
n.nodeid = l.nodeidto::int
where l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
and n.vintersect is null
) t 
on f.nodeidfrom=t.nodeidto
where f.nodeidfrom is null or t.nodeidto is null) tot
join node n2
on tot.nodeid::int=n2.nodeid

In [ ]:
select tot.nodeid, n2.geom from (
	select coalesce(nodeidto, nodeidfrom) nodeid from ( 
		select distinct l.nodeidfrom --nodeidfrom table
		from lion l
		join node n on
		n.nodeid = l.nodeidfrom::int
		where l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
		and n.vintersect is null
		and l.masteridfrom is not null
		and l.masteridto is not null
		) f
		full join
		(
		select distinct l.nodeidto --nodeidto table
		from lion l
		join node n on
		n.nodeid = l.nodeidto::int
		where l.rb_layer in ('R', 'B', 'N') and l.featuretyp not in ('1', '2', '3', '7', 'A', 'F')
		and n.vintersect is null
		and l.masteridfrom is not null
		and l.masteridto is not null
		) t 
	on f.nodeidfrom=t.nodeidto
	where f.nodeidfrom is null or t.nodeidto is null) tot
join node n2
on tot.nodeid::int=n2.nodeid

In [60]:
from sqlalchemy import create_engine
import pyodbc
import psycopg2

sdb = db2.SqlDb('DOT55SQL01', 'FORMS', user='arcgis', db_pass='arcgis') #Database Connection

engine = create_engine('mssql+pyodbc://{user}:{pw}@FORMS'.format(user='arcgis',pw='arcgis'), echo=False)

In [61]:
dead_ends.to_sql(name='dead_ends', con= engine, if_exists = 'replace', index=False)

InterfaceError: (pyodbc.InterfaceError) ('IM002', u'[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: http://sqlalche.me/e/rvf5)